### ISSUE TITLE
Fichier Readme vide

### ISSUE THREAD

**Issue by ghost** [InfoIsfatesDfhi/InfoIsfatesDfhi.github.io#2]
Comment puis je accéder au fichier readme (la liste de liens) ? Dois je copier coller le code source html et les fichiers css ou un lien de la page web est il disponible ?

**Comment by Lyokolux** [comment]
Les liens se trouvent normalement dans le menu de l'organisation, rubrique "Projects"
https://github.com/orgs/InfoIsfatesDfhi/projects/2
